@startuml SQ

autonumber

title SD16. Tạo khóa học

actor "Instructor" as Actor
boundary "views/\nCreateCoursePage" as CreateCoursePage
boundary "views/\nMyCreatedCoursesPage" as MyCreatedCoursesPage
control "CourseService"
control "CourseController"
entity "CourseModel"
database "Database" as Database

activate Actor
Actor -> CreateCoursePage: redirect to ../createCourse
deactivate Actor
activate CreateCoursePage
CreateCoursePage -> CourseService: createCourse(userId)
activate CourseService
CourseService -> CourseController: router.post("/createCourse", createCourse)
activate CourseController
CourseController -> CourseModel: call model
activate CourseModel
CourseModel -> Database: Course.create({userId, title, picture,\ndescription, price, status, visibility})
deactivate CourseModel
activate Database
Database --> CourseController: callback
deactivate Database
CourseController --> CourseService: send res.json
deactivate CourseController
CourseService --> CreateCoursePage: display message
deactivate CourseService
CreateCoursePage -> MyCreatedCoursesPage: navigate("/myCreatedCourses")
deactivate CreateCoursePage
ref over MyCreatedCoursesPage
**SD17. Quản lý danh sách khóa học đã tạo**
end ref

@enduml