@startuml

title SD15. Đăng ký tài khoản giáo viên

actor "Instructor" as Actor
boundary "view/\nRegisterInstructorPage" as RegisterInstructorPage
control "UserService"
control "UserController"

activate Actor
Actor -> RegisterInstructorPage: 1. redirects to ../registerIntructor
deactivate Actor
activate RegisterInstructorPage
RegisterInstructorPage -> UserService: 2. registerInstructor()
activate UserService
UserService -> UserController: 3. router.post("/registerInstructor", registerInstructor)
activate UserController
UserController -> NodeMailer: 4. registerInstructor()
activate NodeMailer
NodeMailer --> UserController: 5. callback
deactivate NodeMailer
UserController --> UserService: 6. sends res.json
deactivate UserController
UserService --> RegisterInstructorPage: 7. displays message
deactivate RegisterInstructorPage
deactivate UserService

@enduml