@startuml

title SD19. Cập nhật chi tiết khóa học

actor "Instructor" as Actor
boundary "view/\nCreateCoursePage" as CreateCoursePage
boundary "view/\nMyCreatedCoursesPage" as MyCreatedCoursesPage
control "CourseService"
control "CourseController"
entity "CourseModel"
database "Database" as Database

@enduml