@startuml

title SD2. Xem danh sách khóa học theo tiêu chí

actor "Student"
boundary "view/\nHomePage" as HomePage
boundary "view/\nCourseIntro" as CourseIntro
boundary "components/\nCourseCard" as CourseCard
control "CourseService"
control "CourseController"
entity "CourseModel"
database "Database"

activate Student
Student -> HomePage: 1. redirects to ../home
deactivate Student
activate HomePage
HomePage -> CourseService: 2. getNewestCourses()
activate CourseService
CourseService -> CourseController: 3. router.get("/", getNewestCourses)
activate CourseController
CourseController -> CourseModel: 4. calls model
activate CourseModel
CourseModel -> Database: 5. Course.find({}).sort({})
activate Database
Database --> CourseController: 6. return List<Course>
CourseController --> CourseService: 7. sends res.json
CourseService --> HomePage: 8. return List<Course>
HomePage -> CourseService: 9. getBestSellerCourses()
CourseService -> CourseController: 10. router.get("/", getBestSellerCourses)
CourseController -> CourseModel: 11. calls model
CourseModel -> Database: 12. Course.find({}).sort({})
deactivate CourseModel
Database --> CourseController: 13. return List<Course>
deactivate Database
CourseController --> CourseService: 14. sends res.json
deactivate CourseController
CourseService --> HomePage: 15. return List<Course>
deactivate CourseService
HomePage -> CourseCard: 16. calls component
activate CourseCard
CourseCard --> HomePage: 17. displays data
deactivate CourseCard

opt User clicks a course
HomePage -> CourseIntro: 18. redirects to ../courseIntro
deactivate HomePage
ref over CourseIntro
**SD5. Xem giới thiệu khóa học**
end ref
end group


@enduml