@startuml

title SD9. Xem thông tin chi tiết giáo viên

actor "Student, Admin" as Actor
boundary "views/\nUserDetailPage" as UserDetailPage
boundary "views/\nCourseIntro" as CourseIntro
boundary "components/\nCourseCard" as CourseCard
entity "UserModel"
control "CourseController"
entity "CourseModel"
database "Database" as Database

activate Actor
Actor -> UserDetailPage: 1. redirects to ../userDetail
deactivate Actor
activate UserDetailPage
UserDetailPage -> UserModel: 2. User.getListCourses()
activate UserModel
UserModel -> CourseController: 3. sends GET request
activate CourseController
CourseController -> CourseModel: 4. calls model
activate CourseModel
CourseModel -> Database: 5. Course.find({user})
deactivate CourseModel
Database --> CourseController: 6. return List<Course>
deactivate Database
CourseController --> UserModel: 7. sends res.json
deactivate CourseController
UserModel --> UserDetailPage: 8. return List<Course>
deactivate UserModel
UserDetailPage -> CourseCard: 9. calls component
activate CourseCard
CourseCard --> UserDetailPage: 10. displays data
deactivate CourseCard

opt User clicks a course
UserDetailPage -> CourseIntro: 11. redirects to ../courseIntro
deactivate UserDetailPage
ref over CourseIntro
**SD5. Xem giới thiệu khóa học**
end ref
end

@enduml