@startuml AOA

(1) -> (2): A (2)
(2) -> (3): B (2)
(2) -down-> (4): C (3)
(3) -[dotted]-> (4): (0)
(4) -> (5): D (5)
(4) -up-> (6): E (3)
(5) -[dotted]-> (6): (0)
(6) -> (7): F (3)
(7) -> (8): G (3)
(8) -> (9): H (5)
(9) -> (10): I (7)
(10) -> (11): J (7)
(10) -down-> (12): K (10)
(11) -[dotted]-> (12): (0)
(12) -down-> (13): L (10)
(9) -down-> (13): M (3)
(13) -> (14): N (3)
(14) -> (15): O (20)
(14) -down-> (16): P (30)
(15) -[dotted]-> (16): (0)
(16) -> (17): Q (10)
(17) -> (18): R (2)
(18) -> (19): S (1)
(18) -down-> (20): T (2)
(19) -[dotted]-> (20): (0)
(20) -> (21): U (2)

@enduml