@startuml AON
left to right direction

map "Bắt đầu" as BD {
    0 => 0
}
map "A (2)" as A {
    0 => 2
    0 => 2
}
map "B (2)" as B {
    2 => 4
    3 => 5
}
map "C (3)" as C {
    2 => 5
    2 => 5
}
map "D (5)" as D {
    5 => 10
    5 => 10
}
map "E (3)" as E {
    5 => 8
    7 => 10
}
map "F (3)" as F {
    10 => 13
    10 => 13
}
map "G (3)" as G {
    13 => 16
    13 => 16
}
map "H (5)" as H {
    16 => 21
    16 => 21
}
map "I (7)" as I {
    21 => 28
    21 => 28
}
map "J (7)" as J {
    28 => 35
    31 => 38
}
map "K (10)" as K {
    28 => 38
    28 => 38
}
map "L (10)" as L {
    38 => 48
    38 => 48
}
map "M (3)" as M {
    21 => 24
    45 => 48
}
map "N (3)" as N {
    48 => 51
    48 => 51
}
map "O (20)" as O {
    51 => 71
    61 => 81
}
map "P (30)" as P {
    51 => 81
    51 => 81
}
map "Q (10)" as Q {
    81 => 91
    81 => 91
}
map "R (2)" as R {
    91 => 93
    91 => 93
}
map "S (1)" as S {
    93 => 94
    94 => 95
}
map "T (2)" as T {
    93 => 95
    93 => 95
}
map "U (2)" as U {
    95 => 97
    95 => 97
}
map "Kết thúc" as KT {
    97 => 97
}

BD --> A
A --> B
A --> C
B --> D
C --> D
B --> E
C --> E
D --> F
E --> F
F --> G
G --> H
H --> I
I --> J
I --> K
J --> L
K --> L
H --> M
L --> N
M --> N
N --> O
N --> P
O --> Q
P --> Q
Q --> R
R --> S
R --> T
T --> U
S --> U
U --> KT

@enduml
