@startuml SQ

autonumber

title SD17b. Create comment
Actor "Instructor"
boundary "UpdateLessonDetails"
boundary "CreateComment"
control "CommentService"
control "CommentController"
entity "CommentModel"
database "Database" as Database

Instructor ->  CreateComment: input content
CreateComment -> CommentService: handleCreate(\n{lessonId, content})
CommentService -> CommentController: createComment(\n{lessonId, content})
CommentController -> CommentModel: call model
CommentModel -> Database: Comment.create()
Database --> CommentController: callback
CommentController --> CommentService: send res.json
CommentService --> CreateComment: callback
alt content is empty 
CreateComment -> CreateComment: display alert
else content is not empty
CreateComment -> UpdateLessonDetails: navigate(\n"/update-lesson-details")
end
@enduml